### ISSUE TITLE
Processes in frontal cortex

### ISSUE THREAD

**Issue by sayanfaraz** [neurotechuoft/Wall-EEG#2]
Need to find processes that occur in the frontal cortex that have a strong enough E-field to be detected by EEG sensors.

**Comment by alisatf** [comment]
[Investigations of the Functional Anatomy of Attention using the Stroop Test.pdf](https://github.com/neurotechuoft/Wall-EEG/files/196160/Investigations.of.the.Functional.Anatomy.of.Attention.using.the.Stroop.Test.pdf)

Summary: Measurements of regional cerebral blood flow by a PET-scan were made on normal subjects while they completed the Stroop test. The first half of the experiment revealed high activation of the right orbito-frontal and bilateral parietal structures during these tests. (In addition, there were highly significant time related focal changes in rCerebral Blood Flow.)
